### PR TITLE
fix: refactor listing model and repo to calculate status

### LINKED ISSUE #60: Buy now can still be unlisted or purchased after it has exceeded the end date
Steps to repro: 

- Navigate to a buy now listing that has ended in the db (back date manually if needs be)
- Owner can unlist although shouldn't be able to
- Buyer can select to buy now, although should not be able to

Will need to verify if new designs required for this.

### PR DESCRIPTION
**Pull request by jmulq**
This fixes the issue where a buy now listing can be unlisted or purchase after it has exceeded the end date.

Fixes #60

### CODE REVIEW

**Review by creativogee — DISMISSED** [review]

File: src/graphql-types/listing.ts [hunk 1]
```diff
@@ -152,6 +150,33 @@ export class Listing extends BaseEntity {
   @property()
   fillDetails?: FillDetails
 
+  @field((type) => Boolean, {
+    nullable: true
+  })
+  @property()
+  cancelled?: boolean
+
+  public isActive() {
```
Comment (anjorinjnr) [inline src/graphql-types/listing.ts:159]: I think you want to make to make this getter fields, so they can be available in the response to the client

**Review by anjorinjnr — CHANGES_REQUESTED** [review]

File: src/graphql-types/listing.ts (hunk 1 above)
Comment (jmulq) [reply src/graphql-types/listing.ts]: Made this and the other two getters fields. Is this needed or shall we just limit it to the `isActive` field?

Changes committed to PR comments. Once approved will rebase and fixup the commit.

**Review by anjorinjnr — DISMISSED** [review]

**Comment by jmulq** [comment]
Resolved conflicts - rebasing as previously approved.
